"""init

Revision ID: 2017efe4901e
Revises:
Create Date: 2023-07-19 22:36:34.075057

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2017efe4901e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("address", sa.String(length=128), nullable=False),
        sa.Column("phone", sa.String(length=11), nullable=False),
        sa.Column("manager", sa.String(length=32), nullable=False),
        sa.Column("landline", sa.String(length=32), nullable=False),
        sa.Column("scale", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_business_address"), "business", ["address"], unique=False)
    op.create_index(op.f("ix_business_created_on"), "business", ["created_on"], unique=False)
    op.create_index(op.f("ix_business_landline"), "business", ["landline"], unique=True)
    op.create_index(op.f("ix_business_manager"), "business", ["manager"], unique=False)
    op.create_index(op.f("ix_business_name"), "business", ["name"], unique=True)
    op.create_index(op.f("ix_business_phone"), "business", ["phone"], unique=True)
    op.create_index(op.f("ix_business_scale"), "business", ["scale"], unique=False)
    op.create_index(op.f("ix_business_updated_on"), "business", ["updated_on"], unique=False)
    op.create_table(
        "goods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("identifier", sa.String(length=32), nullable=True),
        sa.Column("type", sa.String(length=32), nullable=True),
        sa.Column("purchase_price", sa.Float(), nullable=False),
        sa.Column("selling_price", sa.Float(), nullable=False),
        sa.Column("inventory", sa.Integer(), nullable=True),
        sa.Column("sales_volume", sa.Integer(), nullable=True),
        sa.Column("purchase_at", sa.DateTime(), nullable=False),
        sa.Column("supplier", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_goods_created_on"), "goods", ["created_on"], unique=False)
    op.create_index(op.f("ix_goods_identifier"), "goods", ["identifier"], unique=False)
    op.create_index(op.f("ix_goods_inventory"), "goods", ["inventory"], unique=False)
    op.create_index(op.f("ix_goods_name"), "goods", ["name"], unique=True)
    op.create_index(op.f("ix_goods_purchase_at"), "goods", ["purchase_at"], unique=False)
    op.create_index(op.f("ix_goods_sales_volume"), "goods", ["sales_volume"], unique=False)
    op.create_index(op.f("ix_goods_supplier"), "goods", ["supplier"], unique=False)
    op.create_index(op.f("ix_goods_type"), "goods", ["type"], unique=False)
    op.create_index(op.f("ix_goods_updated_on"), "goods", ["updated_on"], unique=False)
    op.create_table(
        "login_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("ip", sa.String(length=128), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("province", sa.String(length=64), nullable=True),
        sa.Column("city", sa.String(length=64), nullable=True),
        sa.Column("is_pc", sa.Boolean(), nullable=True),
        sa.Column("device", sa.String(length=128), nullable=True),
        sa.Column("os", sa.String(length=128), nullable=False),
        sa.Column("browser", sa.String(length=128), nullable=False),
        sa.Column("ua", sa.String(length=512), nullable=False),
        sa.Column("headers", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_login_log_city"), "login_log", ["city"], unique=False)
    op.create_index(op.f("ix_login_log_created_on"), "login_log", ["created_on"], unique=False)
    op.create_index(op.f("ix_login_log_ip"), "login_log", ["ip"], unique=False)
    op.create_index(op.f("ix_login_log_updated_on"), "login_log", ["updated_on"], unique=False)
    op.create_index(op.f("ix_login_log_user_id"), "login_log", ["user_id"], unique=False)
    op.create_table(
        "sale",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("goods_id", sa.Integer(), nullable=False),
        sa.Column("business", sa.Integer(), nullable=False),
        sa.Column("sold_at", sa.DateTime(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("unit_price", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sale_business"), "sale", ["business"], unique=False)
    op.create_index(op.f("ix_sale_created_on"), "sale", ["created_on"], unique=False)
    op.create_index(op.f("ix_sale_goods_id"), "sale", ["goods_id"], unique=False)
    op.create_index(op.f("ix_sale_updated_on"), "sale", ["updated_on"], unique=False)
    op.create_table(
        "supplier",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("address", sa.String(length=128), nullable=False),
        sa.Column("phone", sa.String(length=11), nullable=False),
        sa.Column("manager", sa.String(length=32), nullable=False),
        sa.Column("landline", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_supplier_address"), "supplier", ["address"], unique=False)
    op.create_index(op.f("ix_supplier_created_on"), "supplier", ["created_on"], unique=False)
    op.create_index(op.f("ix_supplier_landline"), "supplier", ["landline"], unique=True)
    op.create_index(op.f("ix_supplier_manager"), "supplier", ["manager"], unique=False)
    op.create_index(op.f("ix_supplier_name"), "supplier", ["name"], unique=True)
    op.create_index(op.f("ix_supplier_phone"), "supplier", ["phone"], unique=True)
    op.create_index(op.f("ix_supplier_updated_on"), "supplier", ["updated_on"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("password", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=11), nullable=True),
        sa.Column("real_name", sa.String(length=11), nullable=True),
        sa.Column("avatar", sa.String(length=256), nullable=True),
        sa.Column("expired_at", sa.DateTime(), nullable=True),
        sa.Column("stopped_on", sa.DateTime(), nullable=True),
        sa.Column("activated", sa.Boolean(), server_default=sa.text("true"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone"),
        sa.UniqueConstraint("username", name="uc_user_username"),
    )
    op.create_index(op.f("ix_user_activated"), "user", ["activated"], unique=False)
    op.create_index(op.f("ix_user_created_on"), "user", ["created_on"], unique=False)
    op.create_index(op.f("ix_user_updated_on"), "user", ["updated_on"], unique=False)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=False)
    op.create_table(
        "user_role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("show", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_role_created_on"), "user_role", ["created_on"], unique=False)
    op.create_index(op.f("ix_user_role_role"), "user_role", ["role"], unique=False)
    op.create_index(op.f("ix_user_role_updated_on"), "user_role", ["updated_on"], unique=False)
    op.create_index(op.f("ix_user_role_user_id"), "user_role", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_role_user_id"), table_name="user_role")
    op.drop_index(op.f("ix_user_role_updated_on"), table_name="user_role")
    op.drop_index(op.f("ix_user_role_role"), table_name="user_role")
    op.drop_index(op.f("ix_user_role_created_on"), table_name="user_role")
    op.drop_table("user_role")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_updated_on"), table_name="user")
    op.drop_index(op.f("ix_user_created_on"), table_name="user")
    op.drop_index(op.f("ix_user_activated"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_supplier_updated_on"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_phone"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_name"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_manager"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_landline"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_created_on"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_address"), table_name="supplier")
    op.drop_table("supplier")
    op.drop_index(op.f("ix_sale_updated_on"), table_name="sale")
    op.drop_index(op.f("ix_sale_goods_id"), table_name="sale")
    op.drop_index(op.f("ix_sale_created_on"), table_name="sale")
    op.drop_index(op.f("ix_sale_business"), table_name="sale")
    op.drop_table("sale")
    op.drop_index(op.f("ix_login_log_user_id"), table_name="login_log")
    op.drop_index(op.f("ix_login_log_updated_on"), table_name="login_log")
    op.drop_index(op.f("ix_login_log_ip"), table_name="login_log")
    op.drop_index(op.f("ix_login_log_created_on"), table_name="login_log")
    op.drop_index(op.f("ix_login_log_city"), table_name="login_log")
    op.drop_table("login_log")
    op.drop_index(op.f("ix_goods_updated_on"), table_name="goods")
    op.drop_index(op.f("ix_goods_type"), table_name="goods")
    op.drop_index(op.f("ix_goods_supplier"), table_name="goods")
    op.drop_index(op.f("ix_goods_sales_volume"), table_name="goods")
    op.drop_index(op.f("ix_goods_purchase_at"), table_name="goods")
    op.drop_index(op.f("ix_goods_name"), table_name="goods")
    op.drop_index(op.f("ix_goods_inventory"), table_name="goods")
    op.drop_index(op.f("ix_goods_identifier"), table_name="goods")
    op.drop_index(op.f("ix_goods_created_on"), table_name="goods")
    op.drop_table("goods")
    op.drop_index(op.f("ix_business_updated_on"), table_name="business")
    op.drop_index(op.f("ix_business_scale"), table_name="business")
    op.drop_index(op.f("ix_business_phone"), table_name="business")
    op.drop_index(op.f("ix_business_name"), table_name="business")
    op.drop_index(op.f("ix_business_manager"), table_name="business")
    op.drop_index(op.f("ix_business_landline"), table_name="business")
    op.drop_index(op.f("ix_business_created_on"), table_name="business")
    op.drop_index(op.f("ix_business_address"), table_name="business")
    op.drop_table("business")
    # ### end Alembic commands ###
