"""add_nullable

Revision ID: 3aad6ec5487c
Revises: 7bbf3b8e52f9
Create Date: 2024-01-22 23:36:12.312811

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3aad6ec5487c"
down_revision: Union[str, None] = "7bbf3b8e52f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("goods", "name", existing_type=sa.VARCHAR(), nullable=False, existing_comment="商品名")
    op.alter_column("supplier", "name", existing_type=sa.VARCHAR(length=32), nullable=False, existing_comment="商家名")
    op.alter_column("supplier", "manager", existing_type=sa.VARCHAR(length=32), nullable=False, existing_comment="经营者名")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("supplier", "manager", existing_type=sa.VARCHAR(length=32), nullable=True, existing_comment="经营者名")
    op.alter_column("supplier", "name", existing_type=sa.VARCHAR(length=32), nullable=True, existing_comment="商家名")
    op.alter_column("goods", "name", existing_type=sa.VARCHAR(), nullable=True, existing_comment="商品名")
    # ### end Alembic commands ###
