"""goods_supplier

Revision ID: 3e8a2269f871
Revises: 5e70d0f08c2e
Create Date: 2024-01-22 23:29:56.641760

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3e8a2269f871"
down_revision: Union[str, None] = "5e70d0f08c2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("goods", sa.Column("last_purchase_at", sa.DateTime(), nullable=True, comment="最近一次入库时间"))
    op.drop_index("ix_goods_purchase_at", table_name="goods")
    op.create_index(op.f("ix_goods_last_purchase_at"), "goods", ["last_purchase_at"], unique=False)
    op.drop_column("goods", "purchase_at")
    op.add_column("supplier", sa.Column("contact_at", sa.DateTime(), nullable=True, comment="建立联系时间"))
    op.add_column("supplier", sa.Column("bank_name", sa.String(length=32), nullable=True, comment="开户行"))
    op.add_column("supplier", sa.Column("bank_account", sa.String(length=32), nullable=True, comment="银行账户"))
    op.add_column("supplier", sa.Column("bank_account_name", sa.String(length=32), nullable=True, comment="银行账户名"))
    op.add_column("supplier", sa.Column("disable", sa.Boolean(), nullable=True, comment="是否禁用"))
    op.add_column("supplier", sa.Column("remark", sa.String(length=128), nullable=True, comment="备注"))
    op.create_index(op.f("ix_supplier_bank_account"), "supplier", ["bank_account"], unique=False)
    op.create_index(op.f("ix_supplier_bank_account_name"), "supplier", ["bank_account_name"], unique=False)
    op.create_index(op.f("ix_supplier_bank_name"), "supplier", ["bank_name"], unique=False)
    op.create_index(op.f("ix_supplier_contact_at"), "supplier", ["contact_at"], unique=False)
    op.create_index(op.f("ix_supplier_disable"), "supplier", ["disable"], unique=False)
    op.create_index(op.f("ix_supplier_remark"), "supplier", ["remark"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_supplier_remark"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_disable"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_contact_at"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_bank_name"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_bank_account_name"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_bank_account"), table_name="supplier")
    op.drop_column("supplier", "remark")
    op.drop_column("supplier", "disable")
    op.drop_column("supplier", "bank_account_name")
    op.drop_column("supplier", "bank_account")
    op.drop_column("supplier", "bank_name")
    op.drop_column("supplier", "contact_at")
    op.add_column(
        "goods", sa.Column("purchase_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment="入库时间")
    )
    op.drop_index(op.f("ix_goods_last_purchase_at"), table_name="goods")
    op.create_index("ix_goods_purchase_at", "goods", ["purchase_at"], unique=False)
    op.drop_column("goods", "last_purchase_at")
    # ### end Alembic commands ###
