"""init

Revision ID: 43a1c6438e43
Revises:
Create Date: 2023-08-16 22:28:43.842858

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43a1c6438e43"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business",
        sa.Column("name", sa.String(length=32), nullable=True, comment="商家名"),
        sa.Column("address", sa.String(length=128), nullable=True, comment="地址"),
        sa.Column("phone", sa.String(length=11), nullable=True, comment="电话，不能与备用电话重复"),
        sa.Column("alternative_phone", sa.String(length=11), nullable=True, comment="备用电话，不能与电话重复"),
        sa.Column("manager", sa.String(length=32), nullable=True, comment="经营者名"),
        sa.Column("landline", sa.String(length=32), nullable=True, comment="座机"),
        sa.Column("scale", sa.Integer(), nullable=True, comment="规模"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        comment="销售商家信息",
    )
    op.create_index(op.f("ix_business_address"), "business", ["address"], unique=False)
    op.create_index(op.f("ix_business_alternative_phone"), "business", ["alternative_phone"], unique=True)
    op.create_index(op.f("ix_business_created_on"), "business", ["created_on"], unique=False)
    op.create_index(op.f("ix_business_landline"), "business", ["landline"], unique=True)
    op.create_index(op.f("ix_business_manager"), "business", ["manager"], unique=False)
    op.create_index(op.f("ix_business_name"), "business", ["name"], unique=True)
    op.create_index(op.f("ix_business_phone"), "business", ["phone"], unique=True)
    op.create_index(op.f("ix_business_scale"), "business", ["scale"], unique=False)
    op.create_index(op.f("ix_business_updated_on"), "business", ["updated_on"], unique=False)
    op.create_table(
        "goods",
        sa.Column("name", sa.String(), nullable=True, comment="商品名"),
        sa.Column("identifier", sa.String(length=32), nullable=True, comment="编号"),
        sa.Column("type", sa.String(length=32), nullable=True, comment="种类"),
        sa.Column("purchase_price", sa.Float(), nullable=True, comment="进价"),
        sa.Column("selling_price", sa.Float(), nullable=True, comment="建议售价"),
        sa.Column("inventory", sa.Integer(), nullable=True, comment="库存"),
        sa.Column("sales", sa.Integer(), nullable=True, comment="销量"),
        sa.Column("month_sales", sa.Integer(), nullable=True, comment="月销量，为0时使用真实数据修改(最近30天该商品销量总和)"),
        sa.Column("purchase_at", sa.DateTime(), nullable=True, comment="入库时间"),
        sa.Column("supplier", sa.Integer(), nullable=True, comment="供应商ID"),
        sa.Column("warranty", sa.Integer(), nullable=True, comment="保质期"),
        sa.Column("notes", sa.Text(), nullable=True, comment="备注"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        comment="商品信息",
    )
    op.create_index(op.f("ix_goods_created_on"), "goods", ["created_on"], unique=False)
    op.create_index(op.f("ix_goods_identifier"), "goods", ["identifier"], unique=False)
    op.create_index(op.f("ix_goods_inventory"), "goods", ["inventory"], unique=False)
    op.create_index(op.f("ix_goods_name"), "goods", ["name"], unique=True)
    op.create_index(op.f("ix_goods_purchase_at"), "goods", ["purchase_at"], unique=False)
    op.create_index(op.f("ix_goods_supplier"), "goods", ["supplier"], unique=False)
    op.create_index(op.f("ix_goods_type"), "goods", ["type"], unique=False)
    op.create_index(op.f("ix_goods_updated_on"), "goods", ["updated_on"], unique=False)
    op.create_table(
        "login_log",
        sa.Column("user_id", sa.BigInteger(), nullable=True, comment="用户ID"),
        sa.Column("ip", sa.String(length=128), nullable=True, comment="IP"),
        sa.Column("port", sa.Integer(), nullable=True, comment="端口"),
        sa.Column("country", sa.String(length=64), nullable=True, comment="国"),
        sa.Column("province", sa.String(length=64), nullable=True, comment="省"),
        sa.Column("city", sa.String(length=64), nullable=True, comment="市"),
        sa.Column("is_pc", sa.Boolean(), nullable=True, comment="是否电脑"),
        sa.Column("device", sa.String(length=128), nullable=True, comment="移动设备名"),
        sa.Column("os", sa.String(length=128), nullable=True, comment="系统"),
        sa.Column("browser", sa.String(length=128), nullable=True, comment="浏览器"),
        sa.Column("ua", sa.String(length=512), nullable=True, comment="UA"),
        sa.Column("headers", sa.JSON(), nullable=True, comment="请求头"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        comment="登录日志",
    )
    op.create_index(op.f("ix_login_log_city"), "login_log", ["city"], unique=False)
    op.create_index(op.f("ix_login_log_created_on"), "login_log", ["created_on"], unique=False)
    op.create_index(op.f("ix_login_log_ip"), "login_log", ["ip"], unique=False)
    op.create_index(op.f("ix_login_log_updated_on"), "login_log", ["updated_on"], unique=False)
    op.create_index(op.f("ix_login_log_user_id"), "login_log", ["user_id"], unique=False)
    op.create_table(
        "sale",
        sa.Column("goods_id", sa.Integer(), nullable=True),
        sa.Column("business", sa.Integer(), nullable=True),
        sa.Column("sold_at", sa.DateTime(), nullable=True),
        sa.Column("sales", sa.Integer(), nullable=True),
        sa.Column("unit_price", sa.Float(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        comment="销售记录",
    )
    op.create_index(op.f("ix_sale_business"), "sale", ["business"], unique=False)
    op.create_index(op.f("ix_sale_created_on"), "sale", ["created_on"], unique=False)
    op.create_index(op.f("ix_sale_goods_id"), "sale", ["goods_id"], unique=False)
    op.create_index(op.f("ix_sale_updated_on"), "sale", ["updated_on"], unique=False)
    op.create_table(
        "supplier",
        sa.Column("name", sa.String(length=32), nullable=True, comment="商家名"),
        sa.Column("address", sa.String(length=128), nullable=True, comment="地址"),
        sa.Column("phone", sa.String(length=11), nullable=True, comment="电话，不能与备用电话重复"),
        sa.Column("alternative_phone", sa.String(length=11), nullable=True, comment="备用电话，不能与电话重复"),
        sa.Column("manager", sa.String(length=32), nullable=True, comment="经营者名"),
        sa.Column("landline", sa.String(length=32), nullable=True, comment="座机"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        comment="供应商信息",
    )
    op.create_index(op.f("ix_supplier_address"), "supplier", ["address"], unique=False)
    op.create_index(op.f("ix_supplier_alternative_phone"), "supplier", ["alternative_phone"], unique=True)
    op.create_index(op.f("ix_supplier_created_on"), "supplier", ["created_on"], unique=False)
    op.create_index(op.f("ix_supplier_landline"), "supplier", ["landline"], unique=True)
    op.create_index(op.f("ix_supplier_manager"), "supplier", ["manager"], unique=False)
    op.create_index(op.f("ix_supplier_name"), "supplier", ["name"], unique=True)
    op.create_index(op.f("ix_supplier_phone"), "supplier", ["phone"], unique=True)
    op.create_index(op.f("ix_supplier_updated_on"), "supplier", ["updated_on"], unique=False)
    op.create_table(
        "user",
        sa.Column("username", sa.String(length=32), nullable=True, comment="用户名"),
        sa.Column("password", sa.String(length=100), nullable=True, comment="密码"),
        sa.Column("phone", sa.String(length=11), nullable=True, comment="电话"),
        sa.Column("real_name", sa.String(length=11), nullable=True, comment="真实姓名"),
        sa.Column("avatar", sa.String(length=256), nullable=True, comment="头像"),
        sa.Column("expired_at", sa.DateTime(), nullable=True, comment="用户Jwt到期时间"),
        sa.Column("stopped_on", sa.DateTime(), nullable=True, comment="账号过期时间"),
        sa.Column("activated", sa.Boolean(), server_default=sa.text("true"), nullable=True, comment="是否启用"),
        sa.Column("creator", sa.BigInteger(), nullable=True, comment="创建人"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone"),
        comment="用户信息",
    )
    op.create_index(op.f("ix_user_activated"), "user", ["activated"], unique=False)
    op.create_index(op.f("ix_user_created_on"), "user", ["created_on"], unique=False)
    op.create_index(op.f("ix_user_creator"), "user", ["creator"], unique=False)
    op.create_index(op.f("ix_user_updated_on"), "user", ["updated_on"], unique=False)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=False)
    op.create_table(
        "user_role",
        sa.Column("role", sa.String(length=64), nullable=True, comment="父权限"),
        sa.Column("user_id", sa.BigInteger(), nullable=True, comment="用户ID"),
        sa.Column("show", sa.String(length=64), nullable=True, comment="子权限"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        comment="用户权限",
    )
    op.create_index(op.f("ix_user_role_created_on"), "user_role", ["created_on"], unique=False)
    op.create_index(op.f("ix_user_role_role"), "user_role", ["role"], unique=False)
    op.create_index(op.f("ix_user_role_updated_on"), "user_role", ["updated_on"], unique=False)
    op.create_index(op.f("ix_user_role_user_id"), "user_role", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_role_user_id"), table_name="user_role")
    op.drop_index(op.f("ix_user_role_updated_on"), table_name="user_role")
    op.drop_index(op.f("ix_user_role_role"), table_name="user_role")
    op.drop_index(op.f("ix_user_role_created_on"), table_name="user_role")
    op.drop_table("user_role")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_updated_on"), table_name="user")
    op.drop_index(op.f("ix_user_creator"), table_name="user")
    op.drop_index(op.f("ix_user_created_on"), table_name="user")
    op.drop_index(op.f("ix_user_activated"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_supplier_updated_on"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_phone"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_name"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_manager"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_landline"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_created_on"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_alternative_phone"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_address"), table_name="supplier")
    op.drop_table("supplier")
    op.drop_index(op.f("ix_sale_updated_on"), table_name="sale")
    op.drop_index(op.f("ix_sale_goods_id"), table_name="sale")
    op.drop_index(op.f("ix_sale_created_on"), table_name="sale")
    op.drop_index(op.f("ix_sale_business"), table_name="sale")
    op.drop_table("sale")
    op.drop_index(op.f("ix_login_log_user_id"), table_name="login_log")
    op.drop_index(op.f("ix_login_log_updated_on"), table_name="login_log")
    op.drop_index(op.f("ix_login_log_ip"), table_name="login_log")
    op.drop_index(op.f("ix_login_log_created_on"), table_name="login_log")
    op.drop_index(op.f("ix_login_log_city"), table_name="login_log")
    op.drop_table("login_log")
    op.drop_index(op.f("ix_goods_updated_on"), table_name="goods")
    op.drop_index(op.f("ix_goods_type"), table_name="goods")
    op.drop_index(op.f("ix_goods_supplier"), table_name="goods")
    op.drop_index(op.f("ix_goods_purchase_at"), table_name="goods")
    op.drop_index(op.f("ix_goods_name"), table_name="goods")
    op.drop_index(op.f("ix_goods_inventory"), table_name="goods")
    op.drop_index(op.f("ix_goods_identifier"), table_name="goods")
    op.drop_index(op.f("ix_goods_created_on"), table_name="goods")
    op.drop_table("goods")
    op.drop_index(op.f("ix_business_updated_on"), table_name="business")
    op.drop_index(op.f("ix_business_scale"), table_name="business")
    op.drop_index(op.f("ix_business_phone"), table_name="business")
    op.drop_index(op.f("ix_business_name"), table_name="business")
    op.drop_index(op.f("ix_business_manager"), table_name="business")
    op.drop_index(op.f("ix_business_landline"), table_name="business")
    op.drop_index(op.f("ix_business_created_on"), table_name="business")
    op.drop_index(op.f("ix_business_alternative_phone"), table_name="business")
    op.drop_index(op.f("ix_business_address"), table_name="business")
    op.drop_table("business")
    # ### end Alembic commands ###
