"""goods_add_image

Revision ID: 5e70d0f08c2e
Revises: 43a1c6438e43
Create Date: 2024-01-18 23:03:35.234639

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e70d0f08c2e"
down_revision: Union[str, None] = "43a1c6438e43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("goods", sa.Column("image", sa.String(length=256), nullable=True, comment="商品图片"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("goods", "image")
    # ### end Alembic commands ###
