"""supplier_disable_default

Revision ID: 7afa56791c28
Revises: 8462d8e405e1
Create Date: 2024-01-22 23:46:05.728708

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7afa56791c28"
down_revision: Union[str, None] = "8462d8e405e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("disable", sa.Boolean(), server_default=sa.text("true"), nullable=True, comment="是否禁用")
    )
    op.create_index(op.f("ix_user_disable"), "user", ["disable"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_disable"), table_name="user")
    op.drop_column("user", "disable")
    # ### end Alembic commands ###
