"""supplier_disable_default

Revision ID: 7bbf3b8e52f9
Revises: 3e8a2269f871
Create Date: 2024-01-22 23:31:31.466440

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7bbf3b8e52f9"
down_revision: Union[str, None] = "3e8a2269f871"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
