"""add_nullable

Revision ID: 8462d8e405e1
Revises: 3aad6ec5487c
Create Date: 2024-01-22 23:38:51.080670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8462d8e405e1'
down_revision: Union[str, None] = '3aad6ec5487c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods', 'last_purchase_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_comment='最近一次入库时间')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods', 'last_purchase_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_comment='最近一次入库时间')
    # ### end Alembic commands ###
